apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbo-deployment
  namespace: turbo-webstack
spec:
  selector:
    matchLabels:
      app: turbo-web
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: turbo-web
    spec:
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: turbo-web-go-pv-claim
        - name: config-vol
          configMap:
            name: turbo-web-config-map-as-f
        - name: secret-vol
          secret:
            secretName: turbo-web-secret-as-f

      containers:
      - name: turbo-web-go
        image: asia.gcr.io/poc-innovation-iot/turbo-web-go:1.0.2
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/tmp/mnt"
          name: vol1
        - mountPath: "/tmp/appconfig"
          name: "config-vol"
        - mountPath: "/tmp/appsecret"
          name: "secret-vol"
        env:
        - name: VERSION
          valueFrom: 
            configMapKeyRef:
              name: turbo-web-config-map
              key: VERSION
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: turbo-web-secret
              key: APP_SECRET