version: "3.4"

services:
  sample-go-web:
    build:
      context: ./
    container_name: sample-go-web
    restart: always
    ports:
      - 8080:8080
    environment:
      APP_VERSION: "1.12"
      APP_SECRET: "Super secret"