apiVersion: v1
kind: Secret
metadata:
  name: turbo-web-secret-as-f
  namespace: turbo-webstack
type: Opaque
data:
  secret.conf: |
    QVBQX1NFQ1JFVD0iWVhOa1lYTXhNak0wQ2c9PSIKREJfVVNFUj10dXJibwpEQl9QQVNTPWFzbGRrbGFzO2xk