apiVersion: v1
kind: Service
metadata:
  name: turbo-web-service
  namespace: turbo-webstack
spec:
  selector:
    app: turbo-web
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080